import {variationsRes} from "../interface/variable.interface";

export const dataVar: variationsRes = {
    "items": [
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        },
        {
            "sku": "20630550020",
            "supplier": "Fruits&Passion",
            "supplierId": 143,
            "category": null,
            "id": 19931,
            "barcode": "776288670944",
            "lastUpdateTime": "2019-10-10 15:11:58",
            "showMarket": true,
            "uploadedImages": [],
            "innerHitIds": null,
            "technicalCard": false,
            "importProperties": []
        }
    ],
    "page": 1,
    "total_count": 35169
}